package com.example.expenseTracker.entity;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@Document
public class Expense {
    @Id
    private String id;
    @NotNull(message = "Name is required")
    private String email;
    private String description;
    @Min(value = 0, message = "Salary must be greater than or equal to 0")
    private double salary;
    private String date;
    private String category;
    private String savings;
    private String status; // paid or unpaid
    private String updatedAt;

public String toString() {// this is used to print the object
        return "Expense{" +
                "id='" + id + '\'' +
                ", email='" + email + '\'' +
                ", description='" + description + '\'' +
                ", salary=" + salary +
                ", date='" + date + '\'' +
                ", category='" + category + '\'' +
                ", savings='" + savings + '\'' +
                ", status='" + status + '\'' +
                ", updatedAt='" + updatedAt + '\'' +
                '}';
    }

    // Constructors, getters, and setters can be generated by Lombok

}
